### ISSUE TITLE
integrate mongodb database into the project

### ISSUE THREAD

**Issue by Mogakamo** [Mogaka-tech/weebuild#26]
Credentials will be dropping soon at the discussions tab that is beside the pull request and you are good to go.

**Comment by precious-adeyinka** [comment]
Can I use an ODM like mongoose, if I am allowed to work on this issue?

**Comment by Mogakamo** [comment]
@precious-adeyinka yeah you can use it but keep in mind that we will be using nodejs for the backend side.
You're highly welcomed to work on it.
I'll be able to work out the project structure before the end of the day.

**Comment by janmesh799** [comment]
hey mogakamo,
i can do this work 
can you assign this to me

**Comment by Mogakamo** [comment]
Hey @janmesh799 let me assign you

**Comment by Mogakamo** [comment]
@janmesh799 could you hold on for like today so that I can switch the app to nextjs app

**Comment by janmesh799** [comment]
sure ✌

**Comment by Mogakamo** [comment]
@janmesh799 you can tell me what you will need to get you started so that I can provide all the details to you

**Comment by janmesh799** [comment]
Actually I don't wnat anything other than name of data base

Fir mongo URI, I will test it for local host 
Then you can change that URI in .env file to your Database's URI

**Comment by Mogakamo** [comment]
The name of the db will be weebuild
